"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"

console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
shell_integration = true
final_space = true

[palette]
  accent = '#e4e4e4'
  accent_text = '#f2f3f8'
  battery_1 = '#d50000'
  battery_2 = '#e7371c'
  battery_3 = '#fc5026'
  battery_4 = '#f4621a'
  battery_5 = '#ff771c'
  battery_6 = '#f98219'
  error = '#c22929'
  primary = '#d75f00'
  primary_text = '#ba3200'
  primary_text_alt = '#fcaf67'
  secondary = '#ff8420'
  success = '#3c9036'

[secondary_prompt]
  template = '╰─{{ if .Root }}#{{else}}❯{{end}}'
  foreground = 'p:primary'
  background = 'transparent'

[transient_prompt]
  template = "{{ if gt .PromptCount 1}}{{ if not .Segments.status_code.Error }}<p:success>╰─ 󰗠</>{{ else }}<p:error>╰─   {{ .Segments.status_code.String }}</>{{ end }} <p:secondary> 󰄉 {{ .Segments.execution_time.FormattedMs }}</>  \n\n{{end}}<p:primary>╭─</><p:accent_text,p:primary>󰃰 {{now|date \"15:04:05\"}}</><p:primary></> "
  foreground = 'p:accent_text'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  trailing_diamond = ''

  [[blocks.segments]]
    alias = 'status_code'
    template = '{{ if gt .PromptCount 1}}╰─ {{ if .Error }}  {{ .String }}{{ else }}󰗠{{ end }}{{end}}'
    foreground = 'p:success'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if .Error }}p:error{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
      status_separator = ' | '

  [[blocks.segments]]
    alias = 'execution_time'
    leading_diamond = ''
    template = '{{ if gt .PromptCount 1}}  󰄉 {{ .FormattedMs }}{{end}}'
    foreground = 'p:secondary'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
      style = 'roundrock'

  [[blocks.segments]]
    template = "{{ if gt .PromptCount 1}}\n{{end}}"
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '   <p:secondary> {{ (div ((sub .PhysicalTotalMemory .PhysicalFreeMemory)|float64)  1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB</>'
    foreground = 'p:accent_text'
    background = 'transparent'
    type = 'sysinfo'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      precision = 2

  [[blocks.segments]]
    template = '{{ if not .Error }}  {{ if lt .Percentage 10 }}󱃍{{ else if lt .Percentage 30 }}󰁺{{ else if lt .Percentage 50 }}󰁼{{ else if lt .Percentage 75 }}󰁿{{ else if lt .Percentage 97 }}󰂁{{ else }}󰁹{{ end }} {{ .Percentage}}%{{ end }}'
    foreground = 'p:battery_6'
    background = 'transparent'
    type = 'battery'
    style = 'plain'
    foreground_templates = ['{{ if lt .Percentage 10 }}p:battery_1{{ end }}', '{{ if lt .Percentage 30 }}p:battery_2{{ end }}', '{{ if lt .Percentage 50 }}p:battery_3{{ end }}', '{{ if lt .Percentage 75 }}p:battery_4{{ end }}', '{{ if lt .Percentage 97 }}p:battery_5{{ end }}']

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }} {{ if .Name }}{{ .Name }}{{  end }}{{ if .Version }}@{{.Version}}{{ end }} on {{ .Type }}{{ end }}'
    foreground = 'p:accent_text'
    background = 'transparent'
    type = 'project'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ if not .Error }}  {{ if .Unsupported }}{{ else }} {{ .Full }}{{  end }}{{ end }}'
    foreground = '#00ffff'
    type = 'dotnet'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ if not .Error }}   {{ .Full }}{{ end }}'
    foreground = '#7FD5EA'
    type = 'go'
    style = 'plain'

    [blocks.segments.cache]
      duration = "1h"
      strategy = "session"


  [[blocks.segments]]
    template = '{{ if not .Error }}   {{ .Full }}{{ end }}'
    foreground = '#da5147'
    type = 'java'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ if not .Error }}   {{ .Full }}{{ end }}'
    foreground = '#906cff'
    type = 'kotlin'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ if not .Error }}   {{ .Full }}{{ end }}'
    foreground = 'blue'
    type = 'lua'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ if not .Error }}   {{ .Full }}{{ end }}'
    foreground = '#6CA35E'
    type = 'node'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ if not .Error }}   {{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full  }}{{ end }}'
    foreground = '#c3db4a'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      display_mode = 'context'

  [[blocks.segments]]
    template = '{{ if not .Error }}   {{ .Full }}{{ end }}'
    foreground = '#e44400'
    type = 'rust'
    style = 'plain'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = '╭─'
    template = ' {{ if .WSL }}WSL on {{end}}{{ .Icon }}'
    foreground = 'p:accent_text'
    background = 'p:primary'
    type = 'os'
    style = 'diamond'

    [blocks.segments.properties]
      alpine = ''
      arch = ''
      cache_duration = 'none'
      centos = ''
      debian = ''
      elementary = ''
      fedora = ''
      gentoo = ''
      linux = ''
      macos = ''
      manjaro = ''
      mint = ''
      opensuse = ''
      raspbian = ''
      ubuntu = '󰕈'
      windows = ' '

  [[blocks.segments]]
    template = ' {{ .Name }} '
    foreground = 'p:accent_text'
    background = 'p:primary'
    type = 'shell'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' <b>{{ .UserName }}{{ if .SSHSession }}@{{ .HostName }}{{ end }}</b> '
    foreground = 'p:primary_text'
    powerline_symbol = ''
    background = 'p:accent'
    type = 'session'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Path }}{{ if not .Writable }} {{ end }} '
    foreground = 'p:accent_text'
    powerline_symbol = ''
    background = 'p:secondary'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_format = '%s'
      folder_icon = '…'
      folder_separator_icon = ' <transparent></> '
      max_depth = 2
      style = 'agnoster_short'

  [[blocks.segments]]
    leading_diamond = '<background,transparent></>'
    trailing_diamond = ''
    template = ' {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if  .Working.Changed }} <transparent></> <p:accent_text> {{ .Working.String }}</p:accent_text>{{  end }}{{ if .Staging.Changed }} <transparent></> <p:accent_text> {{ .Staging.String  }}</p:accent_text>{{ end }}{{ if gt .StashCount 0 }} <transparent></> <p:accent_text>󰆓  {{ .StashCount }}</p:accent_text>{{ end }} '
    foreground = 'p:accent_text'
    background = '#0036aa'
    type = 'git'
    style = 'diamond'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#3300aa{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#54433a{{ end }}', '{{ if gt .Ahead 0 }}#744d89{{ end }}', '{{ if gt .Behind 0 }}#744d89{{ end }}']

    [blocks.segments.properties]
      branch_gone_icon = ''
      branch_icon = ' '
      branch_identical_icon = ''
      branch_max_length = 25
      cache_duration = 'none'
      fetch_stash_count = true
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╰─{{ if .Root }}#{{else}}❯{{end}}'
    foreground = 'p:primary'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '󰖟 {{ .IP }}'
  foreground = 'p:accent_text'
  background = 'p:primary'
  type = 'ipify'
  style = 'diamond'
  tips = ['ip']

  [tooltips.properties]
    http_timeout = 1000
