watch_config_changes: False

rendering_backend: V2

# Customize global config options
global:
  border_width: 4 # Width of the border
  border_offset: -1 # How close the border is to the window edges
  
  # border-radius: Radius of the border's corners. Supported values:
  #   - Auto: Automatically determine the radius
  #   - Square: Sharp corners (radius = 0)
  #   - Round: Fully rounded corners
  #   - RoundSmall: Slightly rounded corners
  #   - Or specify any numeric value for a custom radius
  border_radius: 6


  # border_z_order: Z-order of the border relative to its window. Supported values:
  #   - AboveWindow: Place the border above its window
  #   - BelowWindow: Place the border below its window
  #
  # NOTE: Using 'AboveWindow' may cause the border to flicker when used with some applications
  # that manipulate window layering, leading to z-order conflicts.
  border_z_order: AboveWindow

  # follow_native_border: Follow Windows' behavior for border visibility.
  #
  # Windows already shows or hides native borders depending on a window's type or state
  # (e.g., they're hidden for borderless fullscreen windows). When enabled, this option makes
  # tacky-borders follow that visibility behavior.
  #
  # NOTE: This setting only affects visibility for borders that have been initialized.
  # To make sure a border is initialized in the first place, use window_rules.
  follow_native_border: True

  #active_color:
  #  colors: ["#7F7FD5", "#86A8E7", "#91EAE4"]
  #  direction:
  #    start: [0.0, 0.0] # [0.0, 0.0] is the top left corner (windows api is weird like that)
  #    end: [1.0, 1.0] # [1.0, 1.0] is the bottom right corner
    # colors: ["#7F7FD5", "#8F7FD5", "#91EAE4"]
  active_color:
    colors: ["#D72D28", "#FF7105","#FFC300"]
    direction:
      start: [0.0, 1.0]
      end: [1.0, 0.0]


  inactive_color:
    colors: ["#292929", "#202020"]
    direction:
      start: [0.0, 0.0]
      end: [1.0, 1.0]


  # initialize_delay: Time (in ms) before the border appears after opening a new window
  # unminimize_delay: Time (in ms) before the border appears after unminimizing a window
  #
  # These settings help accommodate window animations (e.g., open or unminimize animations).
  # If window animations are disabled, set these to 0.
  #
  # These can also be used to accomodate border animations (e.g., fade animations).
  initialize_delay: 200
  unminimize_delay: 150

  # animations: Configure animation behavior for window borders
  #   fps: Animation frame rate
  #   active: Animations for active windows
  #   inactive: Animations for inactive windows
  #
  # Supported animation types:
  #   - Spiral
  #   - ReverseSpiral
  #   - Fade
  #
  # Specify animation types and parameters as follows:
  #   active:
  #     - type: Spiral
  #       duration: 1800
  #       easing: Linear
  #
  #     - type: Fade
  #       duration: 200
  #       easing: EaseInOutQuad
  #
  # NOTE: Spiral animations may be resource-intensive on low-end systems.
  animations:
    fps: 30

    active:
      - type: Spiral
        duration: 4000
        easing: Linear
      
      - type: Fade
        duration: 300
        easing: EaseInOutQuad

    inactive:
      - type: Fade
        duration: 300
        easing: EaseInOutQuad
  
    # effects: Configure visual effects for window borders
  #   active: Effects for active windows
  #   inactive: Effects for inactive windows
  #
  # Supported effect types:
  #   - Shadow
  #   - Glow
  #
  # Specify effect types and parameters as follows:
  #   active:
  #    - type: Shadow
  #      radius: 2.0
  #      opacity: 1.0
  #      translation:
  #        x: 0
  #        y: 20
  #
  #    - type: Glow
  #      radius: 8.0
  #      opacity: 1.0
  #
  # NOTE: These effects can significantly increase CPU and GPU usage.
  # Additionally, effects require rendering_backend: V2 to work.
  effects:
    enabled: False

    active:
      - type: Shadow
        radius: 4.0
        opacity: 1.0
        translation:
          x: 0
          y: 0

      - type: Glow
        radius: 8.0
        opacity: 1.0

    inactive:
      - type: Shadow
        radius: 4.0
        opacity: 1.0
        translation:
          x: 0
          y: 0

      - type: Glow
        radius: 8.0
        opacity: 1.0

# Customize config options on a per-app basis
window_rules:
  - match: "Class"
    name: "Windows.UI.Core.CoreWindow"
    enabled: false

  - match: "Class"
    name: "XamlExplorerHostIslandWindow"
    enabled: false

  - match: "Title"
    name: "Flow.Launcher"
    enabled: false

  - match: "Process"
    name: "zebar"
    enabled: false

  - match: "Title"
    name: "keyviz"
    enabled: false

  - match: "Title"
    name: "Counter-Strike 2"
    enabled: false

  - match: "Title"
    name: "Command Palette"
    border_width: 3
    border_radius: RoundSmall
    active_color:
      colors: ["#D72D28", "#8F7FD5", "#91EAE4"]
      direction:
        start: [0.0, 1.0]
        end: [1.0, 0.0]

  - match: "Process"
    name: "PowerToys.PowerLauncher"
    border_width: 3
    border_radius: RoundSmall
    active_color:
      colors: ["#D72D28", "#8F7FD5", "#91EAE4"]
      direction:
        start: [0.0, 1.0]
        end: [1.0, 0.0]


# EXAMPLE CONFIGURATION:
# - match: "Class"               # Currently supports "Class" or "Title"
#   name: "MozillaWindowClass"   # Name of the class or title
#   strategy: "Equals"           # Optional. Currently supports "Equals", "Contains", or "Regex". Defaults to "Equals"
#   border_width: 10             # The next few options are all optional and default to global config if nothing is specified
#   border_radius: -10
#   border_offset: -10
#   active_color: "#ffffff"
#   inactive_color: "#000000"
#   enabled: true                # Optional. Enables or disables the border. Defaults to true. Note: you can't forcibly enable borders yet

